
[listen]
host = "127.0.0.1"
port = 27701

[paths]
# set root_dir as working dir where server data(collections folder) and database(auth.db...) reside
root_dir = "."

# The following section is optional,
# set it up if your server is compiled with tls support
[encryption]
ssl_enable = false
cert_file = ""
key_file = ""
