[package]
name = "ankisyncd"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-multipart = "0.3"
futures-util = "0.3"
bytes="0.5.6"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
flate2 = "1.0"
env_logger = "0.8"
config = "0.11.0"
rand = "0.8.4"
sha2 = "0.9.5"
md5 = "0.7.0"
urlparse = "0.7.3"
hex = "0.4.3"
anki={path="anki/rslib"}
[dependencies.rusqlite]
version = "0.25.1"
features = ["bundled"]



