on: [pull_request]

name: Continuous integration

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest]
        style: [all, default, minimal]
        rust:
          - stable
        

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
          
      # set up and run pre-commit
      - name: Run pre-commit
        run: |
          pip -V
          pip install pre-commit
          pre-commit --version
          pre-commit run --all-files

      # clone and patch anki library  
      - name: Clone patch Anki
        run: |
          sh ./scripts/clone_patch_anki
          ls anki

      - name: Build Ankisyncd
        uses: actions-rs/cargo@v1
        with:
          command: build

  # it is necessary to separate windows ,as patch file differ  
  ci_windows:
    name: ci_on_windows
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      # clone and patch anki library  
      - name: Clone patch Anki
        run: |
          ./scripts/clone_patch_anki.bat
          ls anki

       # set up and run pre-commit
      - name: Run pre-commit
        run: |
          pip -V
          pip install pre-commit
          pre-commit --version
          pre-commit run --all-files

      
      # run build script to build
      - name: Build Ankisyncd
        run: |
          cargo build 
          cargo build --features tls

          


